### ISSUE TITLE
Do you mind if I add this to hubot-aws?

### ISSUE THREAD

**Issue by toadkicker** [mdouglass/hubot-sns#1]
Hello!

I'm putting together the SNS features for hubot-aws (https://github.com/yoheimuta/hubot-aws/pull/47) and this code definitely compliments that effort. It can ship right along side it without modification, and include your comments/credits. If you're ok with that happening let me know!

Thanks,

Todd

**Comment by mdouglass** [comment]
That sounds great to me! I've been wanted to get a larger bit of AWS functionality going so the hubot-aws project looks great. 
Anything you need on the licensing/copyright side to move it over, let me know.
Matt
